name: fitfuture
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  cupertino_icons: ^1.0.8
  percent_indicator: ^4.2.5
  google_fonts: ^6.3.0
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2
  ionicons: ^0.2.2
  firebase_core: ^4.1.1
  change_app_package_name: ^1.5.0
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true

  assets:
    - assets/Images/
    - assets/Icons/launcher_icon.png # Add this so the icon file is recognized

# ðŸ‘‡ Configuration for flutter_launcher_icons
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/Icons/launcher_icon.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#000000"
  image: assets/Icons/launcher_icon.png
  android: true
  ios: true
  android_gravity: center
  fullscreen: true
